# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/alyosha/work/git/mesostat-dev/mesostat/gui/mesostatgui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MesostatGui(object):
    def setupUi(self, MesostatGui):
        MesostatGui.setObjectName("MesostatGui")
        MesostatGui.resize(802, 637)
        self.centralWidget = QtWidgets.QWidget(MesostatGui)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.explorerTab = QtWidgets.QWidget()
        self.explorerTab.setObjectName("explorerTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.explorerTab)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.explorerInnerPathLineEdit = QtWidgets.QLineEdit(self.explorerTab)
        self.explorerInnerPathLineEdit.setEnabled(False)
        self.explorerInnerPathLineEdit.setObjectName("explorerInnerPathLineEdit")
        self.verticalLayout_3.addWidget(self.explorerInnerPathLineEdit)
        self.explorerTableWidget = QtWidgets.QTableWidget(self.explorerTab)
        self.explorerTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.explorerTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.explorerTableWidget.setObjectName("explorerTableWidget")
        self.explorerTableWidget.setColumnCount(2)
        self.explorerTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.explorerTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.explorerTableWidget.setHorizontalHeaderItem(1, item)
        self.verticalLayout_3.addWidget(self.explorerTableWidget)
        self.mainTabWidget.addTab(self.explorerTab, "")
        self.dataTab = QtWidgets.QWidget()
        self.dataTab.setObjectName("dataTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dataTab)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dataMainLayout = QtWidgets.QHBoxLayout()
        self.dataMainLayout.setSpacing(6)
        self.dataMainLayout.setObjectName("dataMainLayout")
        self.dataQueryGroupBox = QtWidgets.QGroupBox(self.dataTab)
        self.dataQueryGroupBox.setMinimumSize(QtCore.QSize(200, 0))
        self.dataQueryGroupBox.setObjectName("dataQueryGroupBox")
        self.dataMainLayout.addWidget(self.dataQueryGroupBox)
        self.dataTableWidget = QtWidgets.QTableWidget(self.dataTab)
        self.dataTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.dataTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.dataTableWidget.setObjectName("dataTableWidget")
        self.dataTableWidget.setColumnCount(0)
        self.dataTableWidget.setRowCount(0)
        self.dataMainLayout.addWidget(self.dataTableWidget)
        self.verticalLayout.addLayout(self.dataMainLayout)
        self.mainTabWidget.addTab(self.dataTab, "")
        self.plotsTab = QtWidgets.QWidget()
        self.plotsTab.setObjectName("plotsTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.plotsTab)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.plotsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.plotTypeLabel = QtWidgets.QLabel(self.groupBox)
        self.plotTypeLabel.setObjectName("plotTypeLabel")
        self.gridLayout.addWidget(self.plotTypeLabel, 0, 0, 1, 1)
        self.plotMinParamSlider = QtWidgets.QSlider(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotMinParamSlider.sizePolicy().hasHeightForWidth())
        self.plotMinParamSlider.setSizePolicy(sizePolicy)
        self.plotMinParamSlider.setOrientation(QtCore.Qt.Horizontal)
        self.plotMinParamSlider.setObjectName("plotMinParamSlider")
        self.gridLayout.addWidget(self.plotMinParamSlider, 5, 1, 1, 1)
        self.plotColorLabel = QtWidgets.QLabel(self.groupBox)
        self.plotColorLabel.setObjectName("plotColorLabel")
        self.gridLayout.addWidget(self.plotColorLabel, 7, 0, 1, 1)
        self.plotMaxParamSlider = QtWidgets.QSlider(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotMaxParamSlider.sizePolicy().hasHeightForWidth())
        self.plotMaxParamSlider.setSizePolicy(sizePolicy)
        self.plotMaxParamSlider.setOrientation(QtCore.Qt.Horizontal)
        self.plotMaxParamSlider.setObjectName("plotMaxParamSlider")
        self.gridLayout.addWidget(self.plotMaxParamSlider, 6, 1, 1, 1)
        self.plotColorComboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotColorComboBox.sizePolicy().hasHeightForWidth())
        self.plotColorComboBox.setSizePolicy(sizePolicy)
        self.plotColorComboBox.setObjectName("plotColorComboBox")
        self.gridLayout.addWidget(self.plotColorComboBox, 7, 1, 1, 1)
        self.plotTypeComboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotTypeComboBox.sizePolicy().hasHeightForWidth())
        self.plotTypeComboBox.setSizePolicy(sizePolicy)
        self.plotTypeComboBox.setObjectName("plotTypeComboBox")
        self.plotTypeComboBox.addItem("")
        self.plotTypeComboBox.addItem("")
        self.gridLayout.addWidget(self.plotTypeComboBox, 0, 1, 1, 1)
        self.plotMaxParamLabel = QtWidgets.QLabel(self.groupBox)
        self.plotMaxParamLabel.setObjectName("plotMaxParamLabel")
        self.gridLayout.addWidget(self.plotMaxParamLabel, 6, 0, 1, 1)
        self.plotParamModeComboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotParamModeComboBox.sizePolicy().hasHeightForWidth())
        self.plotParamModeComboBox.setSizePolicy(sizePolicy)
        self.plotParamModeComboBox.setObjectName("plotParamModeComboBox")
        self.plotParamModeComboBox.addItem("")
        self.plotParamModeComboBox.addItem("")
        self.plotParamModeComboBox.addItem("")
        self.gridLayout.addWidget(self.plotParamModeComboBox, 3, 1, 1, 1)
        self.plotDataOrderComboBox = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotDataOrderComboBox.sizePolicy().hasHeightForWidth())
        self.plotDataOrderComboBox.setSizePolicy(sizePolicy)
        self.plotDataOrderComboBox.setObjectName("plotDataOrderComboBox")
        self.plotDataOrderComboBox.addItem("")
        self.plotDataOrderComboBox.addItem("")
        self.gridLayout.addWidget(self.plotDataOrderComboBox, 1, 1, 1, 1)
        self.plotMinParamLabel = QtWidgets.QLabel(self.groupBox)
        self.plotMinParamLabel.setObjectName("plotMinParamLabel")
        self.gridLayout.addWidget(self.plotMinParamLabel, 5, 0, 1, 1)
        self.plotParamModeLabel = QtWidgets.QLabel(self.groupBox)
        self.plotParamModeLabel.setObjectName("plotParamModeLabel")
        self.gridLayout.addWidget(self.plotParamModeLabel, 3, 0, 1, 1)
        self.plotDataOrderLabel = QtWidgets.QLabel(self.groupBox)
        self.plotDataOrderLabel.setObjectName("plotDataOrderLabel")
        self.gridLayout.addWidget(self.plotDataOrderLabel, 1, 0, 1, 1)
        self.plotExactParamLabel = QtWidgets.QLabel(self.groupBox)
        self.plotExactParamLabel.setObjectName("plotExactParamLabel")
        self.gridLayout.addWidget(self.plotExactParamLabel, 4, 0, 1, 1)
        self.plotExactParamSlider = QtWidgets.QSlider(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotExactParamSlider.sizePolicy().hasHeightForWidth())
        self.plotExactParamSlider.setSizePolicy(sizePolicy)
        self.plotExactParamSlider.setOrientation(QtCore.Qt.Horizontal)
        self.plotExactParamSlider.setObjectName("plotExactParamSlider")
        self.gridLayout.addWidget(self.plotExactParamSlider, 4, 1, 1, 1)
        self.plotReducedParamLabel = QtWidgets.QLabel(self.groupBox)
        self.plotReducedParamLabel.setObjectName("plotReducedParamLabel")
        self.gridLayout.addWidget(self.plotReducedParamLabel, 2, 0, 1, 1)
        self.plotReducedParamComboBox = QtWidgets.QComboBox(self.groupBox)
        self.plotReducedParamComboBox.setObjectName("plotReducedParamComboBox")
        self.plotReducedParamComboBox.addItem("")
        self.plotReducedParamComboBox.addItem("")
        self.gridLayout.addWidget(self.plotReducedParamComboBox, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.plotButton = QtWidgets.QPushButton(self.plotsTab)
        self.plotButton.setObjectName("plotButton")
        self.verticalLayout_2.addWidget(self.plotButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.mainTabWidget.addTab(self.plotsTab, "")
        self.horizontalLayout.addWidget(self.mainTabWidget)
        MesostatGui.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MesostatGui)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 802, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MesostatGui.setMenuBar(self.menuBar)
        self.actionLoad_data = QtWidgets.QAction(MesostatGui)
        self.actionLoad_data.setObjectName("actionLoad_data")
        self.actionLoad_H5 = QtWidgets.QAction(MesostatGui)
        self.actionLoad_H5.setObjectName("actionLoad_H5")
        self.menuFile.addAction(self.actionLoad_data)
        self.menuFile.addAction(self.actionLoad_H5)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MesostatGui)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MesostatGui)

    def retranslateUi(self, MesostatGui):
        _translate = QtCore.QCoreApplication.translate
        MesostatGui.setWindowTitle(_translate("MesostatGui", "MesostatGui"))
        item = self.explorerTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MesostatGui", "New Column"))
        item = self.explorerTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MesostatGui", "Type"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.explorerTab), _translate("MesostatGui", "Explorer"))
        self.dataQueryGroupBox.setTitle(_translate("MesostatGui", "Queries"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.dataTab), _translate("MesostatGui", "Data"))
        self.groupBox.setTitle(_translate("MesostatGui", "Plotting"))
        self.plotTypeLabel.setText(_translate("MesostatGui", "Plot Type"))
        self.plotColorLabel.setText(_translate("MesostatGui", "Color By"))
        self.plotTypeComboBox.setItemText(0, _translate("MesostatGui", "PCA"))
        self.plotTypeComboBox.setItemText(1, _translate("MesostatGui", "tSNE"))
        self.plotMaxParamLabel.setText(_translate("MesostatGui", "MaxParam"))
        self.plotParamModeComboBox.setItemText(0, _translate("MesostatGui", "exact"))
        self.plotParamModeComboBox.setItemText(1, _translate("MesostatGui", "range"))
        self.plotParamModeComboBox.setItemText(2, _translate("MesostatGui", "rangeAvg"))
        self.plotDataOrderComboBox.setItemText(0, _translate("MesostatGui", "rsp"))
        self.plotDataOrderComboBox.setItemText(1, _translate("MesostatGui", "rps"))
        self.plotMinParamLabel.setText(_translate("MesostatGui", "MinParam"))
        self.plotParamModeLabel.setText(_translate("MesostatGui", "ParamMode"))
        self.plotDataOrderLabel.setText(_translate("MesostatGui", "DataOrder"))
        self.plotExactParamLabel.setText(_translate("MesostatGui", "ExactParam"))
        self.plotReducedParamLabel.setText(_translate("MesostatGui", "Reduced Param"))
        self.plotReducedParamComboBox.setItemText(0, _translate("MesostatGui", "r"))
        self.plotReducedParamComboBox.setItemText(1, _translate("MesostatGui", "s"))
        self.plotButton.setText(_translate("MesostatGui", "Plot"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.plotsTab), _translate("MesostatGui", "Plots"))
        self.menuFile.setTitle(_translate("MesostatGui", "File"))
        self.actionLoad_data.setText(_translate("MesostatGui", "Load data..."))
        self.actionLoad_H5.setText(_translate("MesostatGui", "Load H5"))
